# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 895412cc753da37c424e975a474c20e7d6a8dc0360551e52d20a8f2f5aaea99e8f1fe77b6107c51496de3870f777077bd68fb8e2fafc36e89295b1b3f43f08e5

test:
  secret_key_base: 4f9f4282ad36cb4fc55fbd5c5e4a23f43027ef6b7c96e9756117bcf4b13bf785fb9c9f1bc205da1be0213f89be26123d8eb1c76feed4ab695b968286441d4b1a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
